# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Single Page App fallback so routes like /u/yourname work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
